Repository F1rrel/RenewedVillageGrowth, pull requests merged in 2021-02, with the labels that each got.

#37 fix tgr for goal diff < 50%
  town.nut
Labels: bug

#34 Added FIRS 2.1.5 support
  .gitignore
  cargo.nut
Labels: enhancement, savegame upgrade

#42 Fixed industry randomization for zero 1 cargo accepting industries
  industry.nut
Labels: bug

#43 Ignore CZTR cargo LVPT
  cargo.nut
Labels: bug

#44 Code formatting
  cargo.nut
  company.nut
  industry.nut
  info.nut
  license.txt
  main.nut
  readme.txt
  story.nut
  strings.nut
  town.nut
Labels: enhancement

#45 Convert tabs to spaces
  cargo.nut
  info.nut
  town.nut
Labels: enhancement
